server:
  port: 8082
  servlet:
    context-path: /PhoneBook
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: abc_123
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PHNBK_LOCAL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  
  main:
    banner-mode: console
      
